GET http://localhost:8080/task/81f76b44-8104-4d2b-8363-48a96a57d014

Accept: application/json

###
GET http://localhost:8080/task/92c0fced-62e8-4b81-b737-6c7620de08e6

###
GET http://localhost:8080/list

Accept: application/json