
###
POST localhost:8080/task/new

{
    "name": "Task 1",
    "description": "Task 1 description",
    "owner": "012"
}
###
POST localhost:8080/task/new

{
    "name": "Task 2",
    "description": "Task 2 description",
    "owner": "012"
}
###
POST localhost:8080/task/new

{
    "name": "Task 3",
    "description": "Task 3 description",
    "owner": "012"
}
###
POST localhost:8080/task/new

{
    "name": "Task 4",
    "description": "Task 4 description",
    "owner": "012"
}
###
POST localhost:8080/task/new

{
    "name": "Task 5",
    "description": "Task 5 description",
    "owner": "012"
}

POST localhost:8080/task/new

{
    "name": "Task 6",
    "description": "Task 6 description",
    "owner": "012"
}

POST localhost:8080/task/new

{
    "name": "Task 7",
    "description": "Task 7 description",
    "owner": "012"
}

POST localhost:8080/task/new

{
    "name": "Task 8",
    "description": "Task 8 description",
    "owner": "012"
}

POST localhost:8080/task/new

{
    "name": "Task 9",
    "description": "Task 9 description",
    "owner": "012"
}
